### ISSUE TITLE
Add naming of Service Groups

### ISSUE THREAD

**Issue by Florianisme** [phax/phoss-smp#148] opened 2020-11-02 07:49 UTC
We have created many Service Groups and it is becoming increasingly tedious to maintain and manage the Service Groups and Endpoints as only the Participant ID is shown in most places of the UI. 
So far, we always have to keep a seperate spreadsheet at hand, which maps the Participant ID to a customers name.

I think being able to name the Service Group would enhance the User Experience by a lot.
Showing the name from the associated Business Card would be also an option.

**Comment by phax** [comment] 2020-11-02 08:34
That is basically a duplicate of #54

**Closed** 2020-12-09 22:12 UTC
Labels: GUI, enhancement
