### ISSUE TITLE
GUI problem with more than 3200 service groups

### ISSUE THREAD

**Issue by arditkazazi** [phax/phoss-smp#97] opened 2019-03-29 08:43 UTC
Hello, 
it seems there is some problem with using the secured area of the gui with more than 3200 service groups The gui became very slow. From the logs we are seeing al lot of calls like this:
•	2019-03-28 14:40:32,556 INFO  com.helger.peppol.smpserver.data.sql.AbstractSMPJPAEnabledManager - getSMPServiceGroupOfID(iso6523-actorid-upis::9906:it05091100965
 
And errors like this:
•	2019-03-28 14:41:32,148 ERROR com.helger.photon.core.requesttrack.LoggingLongRunningRequestCallback - Long running request. ID=63; millisecs=67506; URL=http://192.168.127.31:9060/secure/

Regards

**Comment by ri4a** [comment] 2020-02-03 22:03
The problem is only with

```
secure/menuitem-service_groups
```

So a workaround for other parts of the UI is to deeplink, e.g. to

```
secure/menuitem-smp_settings
```
That will ask for credentials and redirect, without hitting the non-working page.

**Comment by phax** [comment] 2020-06-26 11:35
V5.2.4 comes with an improved UI:
* If there are more than 1000 ServiceGroups, than endpoints are no longer counted - this heavily speeds up the display process
* The list of Endpoints was split into a page for "List" and one for "Tree" - "List" can handle >50K entries in less than 10 seconds (on my machine) - the "Tree" is as slow as before, because of lack of pagination

Closing this for now.

**Closed by phax** 2020-06-26 11:35 UTC
Labels: GUI, enhancement, pinned
